### PR TITLE
Include tag parameter

### PR DESCRIPTION
**Pull request by PauloFerreira25**
Please accept my Pull Request.

I'm including the tag parameter in deploy, following the Copilot documentation

https://aws.github.io/copilot-cli/docs/commands/deploy/

Thank you for your attention

### CODE REVIEW

**Comment by PauloFerreira25** [comment]
now also solve the task problem:
https://github.com/ksivamuthu/aws-copilot-github-action/issues/180

**Comment by ksivamuthu** [comment]
Changes looks good to me. Will merge it once the run is completed

**Review by ksivamuthu — APPROVED** [review]

**Comment by PauloFerreira25** [comment]
Please, do you have any predictions for when the new release comes out?

**Comment by ksivamuthu** [comment]
@PauloFerreira25  released v.0.0.5

**Comment by kylerozanitis** [comment]
@ksivamuthu @PauloFerreira25  -- was this deployed to the marketplace? It looks like 0.0.4 is the latest version and the `name` flag isn't working as expected: 
Screenshot 2023-08-18 at 11 58 31 AM

**Comment by ksivamuthu** [comment]
I have fixed it. The market place shows the latest version now.

**Comment by kylerozanitis** [comment]
Great, seems to be working now. Thanks!

**Pull request merged**
